Document: cards-500
Title: Debian cards-500 Manual
Author: <insert document author here>
Abstract: This manual describes what cards-500 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cards-500/cards-500.sgml.gz

Format: postscript
Files: /usr/share/doc/cards-500/cards-500.ps.gz

Format: text
Files: /usr/share/doc/cards-500/cards-500.text.gz

Format: HTML
Index: /usr/share/doc/cards-500/html/index.html
Files: /usr/share/doc/cards-500/html/*.html
